version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
    assignees:
      - "dtorannpu"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/coverage-v8"
  - package-ecosystem: "gradle"
    directory: "/backend/"
    schedule:
      interval: "weekly"
    assignees:
      - "dtorannpu"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "dtorannpu"
